name: "CLA Assistant"
on:
  pull_request:
    types: [opened,closed,synchronize]

permissions:
  pull-requests: write
    
jobs:
  check:
    name: 'Check'
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: rijkvanzanten/cla-bot@main
      - if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Hi ${{steps.check.outputs.missing}}!

            Thank you for contributing to Directus! Before we consider your Pull Request, we ask that you sign our Contributor License Agreement (CLA). This is only required for your first Pull Request.

            Please [review the CLA](https://github.com/rijkvanzanten/cla-test/), and sign it by adding your GitHub username to [the contributors.yml file](https://github.com/${{github.repository}}/blob/${{github.head_ref}}/contributors.yml). Thanks!
      - if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: true
    