name: "CLA Assistant"
on:
  pull_request:
    types: [opened,closed,synchronize]

permissions:
  pull-requests: write
    
jobs:
  check:
    name: 'Check'
    runs-on: ubuntu-latest
    steps:
      - uses: rijkvanzanten/cla-bot@main
      - if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: true
      - if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        message: |
          Oh no...
    