name: "CLA Assistant"
on:
  pull_request:
    types: [opened,closed,synchronize]

permissions:
  pull-requests: write
    
jobs:
  check:
    name: 'Check'
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: rijkvanzanten/cla-bot@main
    outputs:
      missing: ${{ steps.check.outputs.missing }}
    
  comment:
    name: 'Comment'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: true
      - if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Oh no... ${{needs.check.missing}}